name: teamxpolicy
description: A new flutter plugin project.
version: 0.0.1
homepage:
publish_to: none
environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  teamxservice:
    git:
      url: https://github.com/appstack21/teamxservice.git
      ref: master # branch name
  pdf_viewer_plugin: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.pankaj.txservice.teamxpolicy
        pluginClass: TeamxpolicyPlugin
      ios:
        pluginClass: TeamxpolicyPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/accident.png
    - assets/images/back.png
    - assets/images/copy.png
    - assets/images/download.png
    - assets/images/header.png
    - assets/images/hospital.png
    - assets/images/mobile.png
    - assets/images/travel.png

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Regular.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
