package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin path_provider_android, io.flutter.plugins.pathprovider.PathProviderPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.britto.pdf_viewer_plugin.PdfViewerPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin pdf_viewer_plugin, dev.britto.pdf_viewer_plugin.PdfViewerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.pankaj.txservice.teamxpolicy.TeamxpolicyPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin teamxpolicy, com.pankaj.txservice.teamxpolicy.TeamxpolicyPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.pankaj.txservice.teamxservice.TeamxservicePlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin teamxservice, com.pankaj.txservice.teamxservice.TeamxservicePlugin", e);
    }
  }
}
